// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj6REau5bEWaGBbIFu73ER_W5bza3GJPU',
    appId: '1:1081449182714:web:004938f0ab7f91ea976043',
    messagingSenderId: '1081449182714',
    projectId: 'campusync-8626d',
    authDomain: 'campusync-8626d.firebaseapp.com',
    storageBucket: 'campusync-8626d.firebasestorage.app',
    measurementId: 'G-NN3BBDW6SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMkV4POKhpoeARXeU8ufPNiydCKi6sIc',
    appId: '1:1081449182714:android:8069bdfce14dbe51976043',
    messagingSenderId: '1081449182714',
    projectId: 'campusync-8626d',
    storageBucket: 'campusync-8626d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-egoaADiAuxL_WDAaJhyq2bR7QmQfBFw',
    appId: '1:1081449182714:ios:f2525860f2f5ad0d976043',
    messagingSenderId: '1081449182714',
    projectId: 'campusync-8626d',
    storageBucket: 'campusync-8626d.firebasestorage.app',
    iosBundleId: 'com.example.campusync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-egoaADiAuxL_WDAaJhyq2bR7QmQfBFw',
    appId: '1:1081449182714:ios:f2525860f2f5ad0d976043',
    messagingSenderId: '1081449182714',
    projectId: 'campusync-8626d',
    storageBucket: 'campusync-8626d.firebasestorage.app',
    iosBundleId: 'com.example.campusync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj6REau5bEWaGBbIFu73ER_W5bza3GJPU',
    appId: '1:1081449182714:web:5b51cf7261bb15d8976043',
    messagingSenderId: '1081449182714',
    projectId: 'campusync-8626d',
    authDomain: 'campusync-8626d.firebaseapp.com',
    storageBucket: 'campusync-8626d.firebasestorage.app',
    measurementId: 'G-7RNLXPXZFQ',
  );
}
